import random
import string
from typing import Dict
from typing import List

import pandas as pd


def generate_random_string(N: int = 10) -> str:
    """
    generates random string

    :param N: random string's length
    :return: random string
    """
    return "".join(  # nosec B311
        random.choices(string.ascii_uppercase + string.digits, k=N)  # nosec B311
    )  # nosec B311


def dataframe_as_list_of_dict(df: pd.DataFrame) -> List[Dict[str, float]]:
    """
    converts dataframe to list of dictionaries

    :param df: target dataframe to convert
    :return: list of dictionaries, which is generated by given dataframe
    """
    ret = []
    keys = list(df.columns)
    for val in df.values:
        ret.append(dict(zip(keys, val)))
    return ret
